apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: DockerMachineTemplate
metadata:
  name: kind-worker-dockermachinetemplate
  namespace: input.context[0].metadata.name
  annotations:
    kform.dev/block-type: data
    kform.dev/resource-type: kubernetes_manifest
    kform.dev/resource-id: dockermachinetemplate
