apiVersion: cluster.x-k8s.io/v1beta1
kind: MachineDeployment
metadata:
  name: input.context[0].metadata.name
  namespace: input.context[0].metadata.namespace
spec:
  clusterName: input.context[0].spec.clusterName
  minReadySeconds: 0
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      cluster.x-k8s.io/cluster-name: input.context[0].spec.clusterName
      topology.cluster.x-k8s.io/deployment-name: input.context[0].metadata.name
      topology.cluster.x-k8s.io/owned: ""
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        cluster.x-k8s.io/cluster-name: input.context[0].spec.clusterName
        topology.cluster.x-k8s.io/deployment-name: input.context[0].metadata.name
        topology.cluster.x-k8s.io/owned: ""
    spec:
      bootstrap:
        configRef:
          apiVersion: kubernetes_manifest.kubeadmconfigtemplate.apiVersion
          kind: kubernetes_manifest.kubeadmconfigtemplate.kind
          name: kubernetes_manifest.kubeadmconfigtemplate.metadata.name
          namespace: input.context[0].metadata.namespace
      clusterName: kubernetes_manifest.cluster[0].metadata.name
      infrastructureRef:
        apiVersion: kubernetes_manifest.dockermachinetemplate[0].apiversion
        kind: kubernetes_manifest.dockermachinetemplate[0].kind
        name: kubernetes_manifest.dockermachinetemplate[0].metadata.name
        namespace: input.context[0].metadata.namespace
      version: input.context[0].spec.version
