apiVersion: claim.nephio.org/v1alpha1
kind: WorkloadCluster
metadata:
  name: workloadcluster
  namespace: x
  annotations:
    kform.dev/block-type: input
    kform.dev/resource-id: cluster
    kform.dev/default: "true"
spec:
  location: us-west1
  workloadCluster:
    selector:
  cni:
    selector:
  storage:
    selector:
  repo:
    selector:
  gitops:
    selector:
