apiVersion: cluster.x-k8s.io/v1beta1
kind: ClusterClass
metadata:
  name: kind
  namespace: default
  annotations:
    kform.dev/block-type: data
    kform.dev/resource-type: kubernetes_manifest
    kform.dev/resource-id: clusterClass