apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: input.cluster[0].metadata.name
  namespace: input.cluster[0].metadata.namespace
spec:
  clusterNetwork:
    pods:
      cidrBlocks:
      - 192.168.0.0/16
    serviceDomain: cluster.local
    services:
      cidrBlocks:
      - 10.128.0.0/12
  topology:
    class: docker
    controlPlane:
      metadata: {}
      replicas: input.cluster[0].spec.replicas
    variables:
    - name: imageRepository
      value: ""
    - name: etcdImageTag
      value: ""
    - name: coreDNSImageTag
      value: ""
    - name: podSecurityStandard
      value:
        audit: restricted
        enabled: true
        enforce: baseline
        warn: restricted
    version: input.cluster[0].spec.version
    #workers:
    #  machineDeployments:
    #  - class: docker-default-worker
    #    name: md-0
    #    replicas: 1