apiVersion: v1
kind: ConfigMap
metadata:
  name: context
  namespace: network-system
  annotations:
    kform.dev/block-type: input
    kform.dev/resource-id: context ## this serves as a way to add default and manage the merge 
    kform.dev/default: "true"
data: 
  configServerImage: ghcr.io/sdcio/config-server:latest
  dataServerImage: ghcr.io/sdcio/data-server:latest